In [6]:
my_list=[1,2,3]

In [7]:
print (my_list)

[1, 2, 3]


In [2]:
import numpy as np

In [10]:
arr=np.array(my_list)

In [12]:
my=[[1,2,3],[4,5,6],[7,8,9]]

In [15]:
arrr=np.array(my)
print(arrr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
#10 elements with equal space from 1 to 5
np.linspace(0,5,10)    

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.random.rand(3,3)

array([[0.58633937, 0.4743231 , 0.48699292],
       [0.18112093, 0.94893065, 0.42541417],
       [0.29247608, 0.66435278, 0.57043988]])

In [26]:
np.random.randint(1,100)

86

In [4]:
shape=np.random.randint(1,100,10)
print (shape)

[78 91 81 97 15 51  4 20 56 68]


In [34]:
shape=shape.reshape(5,2)

In [31]:
print(shape.max())
print(shape.min())

86
19


In [41]:
#index of max element
print(shape.argmax())

8


In [35]:
shape.shape


(5, 2)

In [47]:
shape.dtype=="int32"

True

In [33]:
parthiv=np.arange(1,11)

In [34]:
parthiv

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
parthiv1=parthiv>5

In [36]:
parthiv1


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
parthiv[parthiv1]

array([ 6,  7,  8,  9, 10])

In [38]:
parthiv


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
parthiv[parthiv>4]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
parthiv+parthiv

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [83]:
np.max(parthiv)

1.0

In [84]:
np.sqrt(parthiv)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [85]:
np.log(parthiv)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])